---
name: Test & Quality
on: [ push, pull_request ]
jobs:
  test:
    strategy:
      matrix:
        go-version:
          - stable
          - oldstable
        os:
          - ubuntu-latest
        #  - macos-latest
        #arch:
        #  - amd64
        #  - ppc64le
        #  - s390x
        #  - arm64
    runs-on: ${{ matrix.os }}
    env:
      GO111MODULE: on
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Install Go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go-version }}
      - name: Fetch dependencies
        run: go mod download
      - name: Test
        run: go test -v ./...

  quality:
    needs: [ test ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          # Default is 1 (shallow clone with a single commit)
          # but SonarQube wants full history
          fetch-depth: 0
      - name: Install Go
        uses: actions/setup-go@v6
        with:
          go-version: stable
      - name: Test (JSON, for SonarQube)
        # Powershell has issues with '=' in args
        run: go test -json -covermode atomic -coverpkg ./... -coverprofile .coverage.out ./... >.gotest.out

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v7
        env:
          # https://sonarcloud.io/project/configuration/GitHubActions?id=dolmen-go_kittyimg
          # https://github.com/dolmen-go/kittyimg/settings/secrets/actions
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          # See also sonar-project.properties
          args: >
            -Dsonar.go.tests.reportPaths=.gotest.out
            -Dsonar.go.coverage.reportPaths=.coverage.out

      - name: Upload coverage to Codecov.io
        # https://github.com/codecov/codecov-action
        # https://docs.codecov.com/docs/quick-start
        uses: codecov/codecov-action@v5
        with:
          # https://app.codecov.io/gh/dolmen-go/kittyimg/settings
          # https://github.com/dolmen-go/kittyimg/settings/secrets/actions
          token: ${{ secrets.CODECOV_TOKEN }}
